export const FETCH_ORDERS = 'FETCH_ORDERS';

export const QUERY_ORDERS = 'QUERY_ORDERS';

export const SAVE_ORDER = 'SAVE_ORDER';

export const QUERY_STATUS = 'QUERY_STATUS';

export const LOGIN = 'LOGIN';

export const QUERY_LOG_MESSAGES = "QUERY_LOG_MESSAGES";

export const CLOSE_ORDER = "STOP_ORDER";

export const REMOVE_STRATEGY = "REMOVE_STRATEGY";

export const SAVE_SETTING = "SAVE_SETTING";

export const REMOVE_SETTING = "REMOVE_SETTING";

export const LIST_SETTINGS = "LIST_SETTINGS";

export const LIST_ACCOUNT_SETTINGS = "LIST_ACCOUNT_SETTINGS";

export const REMOVE_ORDER = "REMOVE_ORDER";

export const FETCH_ACCOUNTS = "LIST_ACCOUNTS";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT";

export const LIST_STRATEGY_NAMES = "LIST_STRATEGY_NAMES";

export const REMOVE_ACCOUNT = "REMOVE_ACCOUNT";

export const ACCOUNT_ALERT_ADD = "ACCOUNT_ALERT_ADD";

export const ACCOUNT_ALERT_LIST = "ACCOUNT_ALERT_LIST"

export const ACCOUNT_ALERT_DELETE = "ACCOUNT_ALERT_DELETE"
