export const ORDER_LIST = 'ORDER_LIST';

export const CLEAR_ORDERS = "CLEAR_ORDERS";

export const SHOW_DIALOG = 'SHOW_DIALOG';

export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const FOREXWATCH_STATUS = 'FOREXWATCH_STATUS';

export const IS_LOADING = "IS_LOADING";

export const LOGIN_SUCCESFUL = "LOGIN_SUCCESFUL";

export const LOGIN_UNSUCCESFUL = "LOGIN_UNSUCCESFUL";

export const LIST_COMPILED_STRATEGIES = "LIST_COMPILED__STRATEGIES";

export const STRATEGY_STARTED = "STRATEGY_STARTED";

export const STRATEGY_STOPPED = "STRATEGY_STOPPED";

export const LOADED_JARS = "LOADED_JARS";

export const JAR_COMPILED = "JAR_COMPILED";

export const LOG_MESSAGE_LIST = "LOG_MESSAGE_LIST";

export const CLEAR_LOG_MESSAGES = "CLEAR_LOG_MESSAGES";

export const SELECTED_SETTING = "SELECTED_SETTING";

export const SETTINGS_LIST = "SETTINGS_LIST";

export const SETTING_SAVED = "SETTING_SAVED";

export const ACCOUNTS_LIST = "ACCOUNTS_LIST";

export const ACCOUNT_EDIT = "ACCOUNT_EDIT";

export const ORDER_SELECTED = "ORDER_SELECTED";

export const STRATEGY_NAMES_LIST = "STRATEGY_NAMES_LIST";

export const ACCOUNT_REMOVED = "ACCOUNT_REMOVED";

export const MESSAGE_ADD = "MESSAGE_ADD";

export const MESSAGE_REMOVE = "MESSAGE_REMOVE";

export const ACCOUNT_ALERTS_LISTED = "ACCOUNT_ALERTS_LISTED"

export const ACCOUNT_ALERT_DELETED = "ACCOUNT_ALERT_DELETED"

export const ACCOUNT_ALERT_ADDED = "ACCOUNT_ALERT_ADDED"
