apiVersion: v1
kind: Pod
metadata:
  labels:
    run: skolli
  name: skolli
spec:
  containers:
    - image: mcr.microsoft.com/mssql/server
      name: skolli
      env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Salis123
        - name: MSSQL_PID
          value: Developer
      ports:
        - containerPort: 1433
          name: skolli
---
apiVersion: v1
kind: Service
metadata:
  name: skolli
spec:
  type: NodePort
  ports:
    - port: 1433
      nodePort: 31433
  selector:
    run: skolli